version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_API_URL=${CLERK_API_URL}
      - PORT=8000
    restart: unless-stopped