services:
  - type: web
    name: gradguide-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_API_URL
        sync: false