services:
  - type: web
    name: gradguide-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT 
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: anthropic/claude-3-haiku
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_API_URL
        value: https://api.clerk.dev/v1